{
  "flightStatusMessages" : [ {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "TCMAGT82TCM"
        } ]
      },
      "creationDate" : "2017-06-13T17:40:00",
      "edifactData" : {
        "commonAccessReference" : "1706131740",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21574933"
      }
    },
    "airWaybillNumber" : "020-67431523",
    "originAndDestination" : {
      "origin" : "ZRH",
      "destination" : "MEX"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 9.1,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "received from shipper",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 9.1,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-13T18:13:00",
      "airportOfReceipt" : "ZRH",
      "receivedFromName" : "DSV LOGISTICS AG"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "TDVAGT03DSV/ZRH1"
        } ]
      },
      "creationDate" : "2017-06-13T17:40:00",
      "edifactData" : {
        "commonAccessReference" : "1706131740",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21574937"
      }
    },
    "airWaybillNumber" : "020-67431523",
    "originAndDestination" : {
      "origin" : "ZRH",
      "destination" : "MEX"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 9.1,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "received from shipper",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 9.1,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-13T18:13:00",
      "airportOfReceipt" : "ZRH",
      "receivedFromName" : "DSV LOGISTICS AG"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "TCMAGT82TCM"
        } ]
      },
      "creationDate" : "2017-06-14T06:43:00",
      "edifactData" : {
        "commonAccessReference" : "1706140643",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21622060"
      }
    },
    "airWaybillNumber" : "020-67431523",
    "originAndDestination" : {
      "origin" : "ZRH",
      "destination" : "MEX"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 9.1,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "departed",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 9.1,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-14T08:08:00",
      "flight" : "LH1183",
      "dateOfScheduledDeparture" : "2017-06-14",
      "origin" : "ZRH",
      "destination" : "FRA",
      "timeOfScheduledArrival" : "2017-06-14T09:20:00"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "TDVAGT03DSV/ZRH1"
        } ]
      },
      "creationDate" : "2017-06-14T06:43:00",
      "edifactData" : {
        "commonAccessReference" : "1706140643",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21622062"
      }
    },
    "airWaybillNumber" : "020-67431523",
    "originAndDestination" : {
      "origin" : "ZRH",
      "destination" : "MEX"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 9.1,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "departed",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 9.1,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-14T08:08:00",
      "flight" : "LH1183",
      "dateOfScheduledDeparture" : "2017-06-14",
      "origin" : "ZRH",
      "destination" : "FRA",
      "timeOfScheduledArrival" : "2017-06-14T09:20:00"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "TCMAGT82TCM"
        } ]
      },
      "creationDate" : "2017-06-14T06:43:00",
      "edifactData" : {
        "commonAccessReference" : "1706140643",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21622081"
      }
    },
    "airWaybillNumber" : "020-67431523",
    "originAndDestination" : {
      "origin" : "ZRH",
      "destination" : "MEX"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 9.1,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "booked",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 9.1,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-14T06:43:24.664",
      "flight" : "LH1183",
      "dateOfScheduledDeparture" : "2017-06-14",
      "origin" : "ZRH",
      "destination" : "FRA",
      "timeOfScheduledDeparture" : "2017-06-14T08:15:00",
      "timeOfScheduledArrival" : "2017-06-14T09:20:00"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "TDVAGT03DSV/ZRH1"
        } ]
      },
      "creationDate" : "2017-06-14T06:43:00",
      "edifactData" : {
        "commonAccessReference" : "1706140643",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21622084"
      }
    },
    "airWaybillNumber" : "020-67431523",
    "originAndDestination" : {
      "origin" : "ZRH",
      "destination" : "MEX"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 9.1,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "booked",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 9.1,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-14T06:43:24.668",
      "flight" : "LH1183",
      "dateOfScheduledDeparture" : "2017-06-14",
      "origin" : "ZRH",
      "destination" : "FRA",
      "timeOfScheduledDeparture" : "2017-06-14T08:15:00",
      "timeOfScheduledArrival" : "2017-06-14T09:20:00"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "TCMAGT82TCM"
        } ]
      },
      "creationDate" : "2017-06-14T06:43:00",
      "edifactData" : {
        "commonAccessReference" : "1706140643",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21622081"
      }
    },
    "airWaybillNumber" : "020-67431523",
    "originAndDestination" : {
      "origin" : "ZRH",
      "destination" : "MEX"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 9.1,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "booked",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 9.1,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-14T06:43:24.762",
      "flight" : "LH0498",
      "dateOfScheduledDeparture" : "2017-06-14",
      "origin" : "FRA",
      "destination" : "MEX",
      "timeOfScheduledDeparture" : "2017-06-14T13:25:00",
      "timeOfScheduledArrival" : "2017-06-14T18:20:00"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "TDVAGT03DSV/ZRH1"
        } ]
      },
      "creationDate" : "2017-06-14T06:43:00",
      "edifactData" : {
        "commonAccessReference" : "1706140643",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21622084"
      }
    },
    "airWaybillNumber" : "020-67431523",
    "originAndDestination" : {
      "origin" : "ZRH",
      "destination" : "MEX"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 9.1,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "booked",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 9.1,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-14T06:43:24.797",
      "flight" : "LH0498",
      "dateOfScheduledDeparture" : "2017-06-14",
      "origin" : "FRA",
      "destination" : "MEX",
      "timeOfScheduledDeparture" : "2017-06-14T13:25:00",
      "timeOfScheduledArrival" : "2017-06-14T18:20:00"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "TCMAGT82TCM"
        } ]
      },
      "creationDate" : "2017-06-14T07:05:00",
      "edifactData" : {
        "commonAccessReference" : "1706140705",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21624600"
      }
    },
    "airWaybillNumber" : "020-67431523",
    "originAndDestination" : {
      "origin" : "ZRH",
      "destination" : "MEX"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 9.1,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "arrived",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 9.1,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-14T09:02:00",
      "flight" : "LH1183",
      "dateOfScheduledArrival" : "2017-06-14",
      "destination" : "FRA"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "TDVAGT03DSV/ZRH1"
        } ]
      },
      "creationDate" : "2017-06-14T07:05:00",
      "edifactData" : {
        "commonAccessReference" : "1706140705",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21624601"
      }
    },
    "airWaybillNumber" : "020-67431523",
    "originAndDestination" : {
      "origin" : "ZRH",
      "destination" : "MEX"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 9.1,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "arrived",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 9.1,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-14T09:02:00",
      "flight" : "LH1183",
      "dateOfScheduledArrival" : "2017-06-14",
      "destination" : "FRA"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "TCMAGT82TCM"
        } ]
      },
      "creationDate" : "2017-06-14T08:03:00",
      "edifactData" : {
        "commonAccessReference" : "1706140803",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21630297"
      }
    },
    "airWaybillNumber" : "020-67431523",
    "originAndDestination" : {
      "origin" : "ZRH",
      "destination" : "MEX"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 9.1,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "received from flight",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 9.1,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-14T10:02:00",
      "flight" : "LH1183",
      "dateOfScheduledArrival" : "2017-06-14",
      "destination" : "FRA"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "TDVAGT03DSV/ZRH1"
        } ]
      },
      "creationDate" : "2017-06-14T08:03:00",
      "edifactData" : {
        "commonAccessReference" : "1706140803",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21630298"
      }
    },
    "airWaybillNumber" : "020-67431523",
    "originAndDestination" : {
      "origin" : "ZRH",
      "destination" : "MEX"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 9.1,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "received from flight",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 9.1,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-14T10:02:00",
      "flight" : "LH1183",
      "dateOfScheduledArrival" : "2017-06-14",
      "destination" : "FRA"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "TCMAGT82TCM"
        } ]
      },
      "creationDate" : "2017-06-14T14:59:00",
      "edifactData" : {
        "commonAccessReference" : "1706141459",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21674734"
      }
    },
    "airWaybillNumber" : "020-67431523",
    "originAndDestination" : {
      "origin" : "ZRH",
      "destination" : "MEX"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 9.1,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "departed",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 9.1,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-14T14:01:00",
      "flight" : "LH498",
      "dateOfScheduledDeparture" : "2017-06-14",
      "origin" : "FRA",
      "destination" : "MEX",
      "timeOfScheduledArrival" : "2017-06-14T18:20:00"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "TDVAGT03DSV/ZRH1"
        } ]
      },
      "creationDate" : "2017-06-14T14:59:00",
      "edifactData" : {
        "commonAccessReference" : "1706141459",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21674735"
      }
    },
    "airWaybillNumber" : "020-67431523",
    "originAndDestination" : {
      "origin" : "ZRH",
      "destination" : "MEX"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 9.1,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "departed",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 9.1,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-14T14:01:00",
      "flight" : "LH498",
      "dateOfScheduledDeparture" : "2017-06-14",
      "origin" : "FRA",
      "destination" : "MEX",
      "timeOfScheduledArrival" : "2017-06-14T18:20:00"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "TCMAGT82TCM"
        } ]
      },
      "creationDate" : "2017-06-14T23:21:00",
      "edifactData" : {
        "commonAccessReference" : "1706142321",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21717873"
      }
    },
    "airWaybillNumber" : "020-67431523",
    "originAndDestination" : {
      "origin" : "ZRH",
      "destination" : "MEX"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 9.1,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "arrived",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 9.1,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-14T18:19:00",
      "flight" : "LH498",
      "dateOfScheduledArrival" : "2017-06-14",
      "destination" : "MEX"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "TDVAGT03DSV/ZRH1"
        } ]
      },
      "creationDate" : "2017-06-14T23:21:00",
      "edifactData" : {
        "commonAccessReference" : "1706142321",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21717874"
      }
    },
    "airWaybillNumber" : "020-67431523",
    "originAndDestination" : {
      "origin" : "ZRH",
      "destination" : "MEX"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 9.1,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "arrived",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 9.1,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-14T18:19:00",
      "flight" : "LH498",
      "dateOfScheduledArrival" : "2017-06-14",
      "destination" : "MEX"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "TCMAGT82TCM"
        } ]
      },
      "creationDate" : "2017-06-15T03:23:00",
      "edifactData" : {
        "commonAccessReference" : "1706150323",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21730478"
      }
    },
    "airWaybillNumber" : "020-67431523",
    "originAndDestination" : {
      "origin" : "ZRH",
      "destination" : "MEX"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 9.1,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "received from flight",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 9.1,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-14T22:23:00",
      "flight" : "LH498",
      "dateOfScheduledArrival" : "2017-06-14",
      "destination" : "MEX"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "TDVAGT03DSV/ZRH1"
        } ]
      },
      "creationDate" : "2017-06-15T03:23:00",
      "edifactData" : {
        "commonAccessReference" : "1706150323",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21730479"
      }
    },
    "airWaybillNumber" : "020-67431523",
    "originAndDestination" : {
      "origin" : "ZRH",
      "destination" : "MEX"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 9.1,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "received from flight",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 9.1,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-14T22:23:00",
      "flight" : "LH498",
      "dateOfScheduledArrival" : "2017-06-14",
      "destination" : "MEX"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "TDVAGT03DSV/ZRH1"
        } ]
      },
      "creationDate" : "2017-06-15T03:23:00",
      "edifactData" : {
        "commonAccessReference" : "1706150323",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21730512"
      }
    },
    "airWaybillNumber" : "020-67431523",
    "originAndDestination" : {
      "origin" : "ZRH",
      "destination" : "MEX"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 9.1,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "consignee notified",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 9.1,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-14T22:23:00",
      "airportOfNotification" : "MEX",
      "notificationToName" : "DSV AIR   SEA S.A. DE C.V.-I930"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "TCMAGT82TCM"
        } ]
      },
      "creationDate" : "2017-06-15T03:23:00",
      "edifactData" : {
        "commonAccessReference" : "1706150323",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21730511"
      }
    },
    "airWaybillNumber" : "020-67431523",
    "originAndDestination" : {
      "origin" : "ZRH",
      "destination" : "MEX"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 9.1,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "consignee notified",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 9.1,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-14T22:23:00",
      "airportOfNotification" : "MEX",
      "notificationToName" : "DSV AIR   SEA S.A. DE C.V.-I930"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "TDVAGT03DSV/ZRH1"
        } ]
      },
      "creationDate" : "2017-06-15T12:49:00",
      "edifactData" : {
        "commonAccessReference" : "1706151249",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21777019"
      }
    },
    "airWaybillNumber" : "020-67431523",
    "originAndDestination" : {
      "origin" : "ZRH",
      "destination" : "MEX"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 9.1,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "delivered",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 9.1,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-15T07:49:00",
      "airportOfDelivery" : "MEX",
      "deliveryToName" : "TALMA"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "TCMAGT82TCM"
        } ]
      },
      "creationDate" : "2017-06-15T12:49:00",
      "edifactData" : {
        "commonAccessReference" : "1706151249",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21777018"
      }
    },
    "airWaybillNumber" : "020-67431523",
    "originAndDestination" : {
      "origin" : "ZRH",
      "destination" : "MEX"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 9.1,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "delivered",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 9.1,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-15T07:49:00",
      "airportOfDelivery" : "MEX",
      "deliveryToName" : "TALMA"
    } ]
  } ],
  "responseCode" : "OK"
}