{
  "flightStatusMessages" : [ {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAGT82SHNK/CTA01"
        } ]
      },
      "creationDate" : "2017-06-13T20:19:00",
      "edifactData" : {
        "commonAccessReference" : "1706132019",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21587623"
      }
    },
    "airWaybillNumber" : "020-77353780",
    "originAndDestination" : {
      "origin" : "VRN",
      "destination" : "ORD"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 250,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "arrived",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 250,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-13T22:18:00",
      "flight" : "LH7535S",
      "dateOfScheduledArrival" : "2017-06-13",
      "destination" : "FRA"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "TCMAGT82TCM"
        } ]
      },
      "creationDate" : "2017-06-13T20:19:00",
      "edifactData" : {
        "commonAccessReference" : "1706132019",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21587621"
      }
    },
    "airWaybillNumber" : "020-77353780",
    "originAndDestination" : {
      "origin" : "VRN",
      "destination" : "ORD"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 250,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "arrived",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 250,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-13T22:18:00",
      "flight" : "LH7535S",
      "dateOfScheduledArrival" : "2017-06-13",
      "destination" : "FRA"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "TCMAGT82TCM"
        } ]
      },
      "creationDate" : "2017-06-13T21:47:00",
      "edifactData" : {
        "commonAccessReference" : "1706132147",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21594127"
      }
    },
    "airWaybillNumber" : "020-77353780",
    "originAndDestination" : {
      "origin" : "VRN",
      "destination" : "ORD"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 250,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "received from flight",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 250,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-13T23:47:00",
      "flight" : "LH7535S",
      "dateOfScheduledArrival" : "2017-06-13",
      "destination" : "FRA"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAGT82SHNK/CTA01"
        } ]
      },
      "creationDate" : "2017-06-13T21:47:00",
      "edifactData" : {
        "commonAccessReference" : "1706132147",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21594128"
      }
    },
    "airWaybillNumber" : "020-77353780",
    "originAndDestination" : {
      "origin" : "VRN",
      "destination" : "ORD"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 250,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "received from flight",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 250,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-13T23:47:00",
      "flight" : "LH7535S",
      "dateOfScheduledArrival" : "2017-06-13",
      "destination" : "FRA"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAGT82SHNK/CTA01"
        } ]
      },
      "creationDate" : "2017-06-14T17:38:00",
      "edifactData" : {
        "commonAccessReference" : "1706141738",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21689518"
      }
    },
    "airWaybillNumber" : "020-77353780",
    "originAndDestination" : {
      "origin" : "VRN",
      "destination" : "ORD"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 250,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "departed",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 250,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-14T17:23:00",
      "flight" : "LH432",
      "dateOfScheduledDeparture" : "2017-06-14",
      "origin" : "FRA",
      "destination" : "ORD",
      "timeOfScheduledArrival" : "2017-06-14T19:15:00"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "TCMAGT82TCM"
        } ]
      },
      "creationDate" : "2017-06-14T17:38:00",
      "edifactData" : {
        "commonAccessReference" : "1706141738",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21689517"
      }
    },
    "airWaybillNumber" : "020-77353780",
    "originAndDestination" : {
      "origin" : "VRN",
      "destination" : "ORD"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 250,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "departed",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 250,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-14T17:23:00",
      "flight" : "LH432",
      "dateOfScheduledDeparture" : "2017-06-14",
      "origin" : "FRA",
      "destination" : "ORD",
      "timeOfScheduledArrival" : "2017-06-14T19:15:00"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "TCMAGT82TCM"
        } ]
      },
      "creationDate" : "2017-06-15T00:15:00",
      "edifactData" : {
        "commonAccessReference" : "1706150015",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21720976"
      }
    },
    "airWaybillNumber" : "020-77353780",
    "originAndDestination" : {
      "origin" : "VRN",
      "destination" : "ORD"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 250,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "arrived",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 250,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-14T19:15:00",
      "flight" : "LH432",
      "dateOfScheduledArrival" : "2017-06-14",
      "destination" : "ORD"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAGT82SHNK/CTA01"
        } ]
      },
      "creationDate" : "2017-06-15T00:15:00",
      "edifactData" : {
        "commonAccessReference" : "1706150015",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21720979"
      }
    },
    "airWaybillNumber" : "020-77353780",
    "originAndDestination" : {
      "origin" : "VRN",
      "destination" : "ORD"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 250,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "arrived",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 250,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-14T19:15:00",
      "flight" : "LH432",
      "dateOfScheduledArrival" : "2017-06-14",
      "destination" : "ORD"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAGT82SHNK/CTA01"
        } ]
      },
      "creationDate" : "2017-06-15T02:06:00",
      "edifactData" : {
        "commonAccessReference" : "1706150206",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21726278"
      }
    },
    "airWaybillNumber" : "020-77353780",
    "originAndDestination" : {
      "origin" : "VRN",
      "destination" : "ORD"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 250,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "received from flight",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 250,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-14T21:06:00",
      "flight" : "LH432",
      "dateOfScheduledArrival" : "2017-06-14",
      "destination" : "ORD"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "TCMAGT82TCM"
        } ]
      },
      "creationDate" : "2017-06-15T02:06:00",
      "edifactData" : {
        "commonAccessReference" : "1706150206",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21726277"
      }
    },
    "airWaybillNumber" : "020-77353780",
    "originAndDestination" : {
      "origin" : "VRN",
      "destination" : "ORD"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 250,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "received from flight",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 250,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-14T21:06:00",
      "flight" : "LH432",
      "dateOfScheduledArrival" : "2017-06-14",
      "destination" : "ORD"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAGT82SHNK/CTA01"
        } ]
      },
      "creationDate" : "2017-06-15T02:06:00",
      "edifactData" : {
        "commonAccessReference" : "1706150206",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21726276"
      }
    },
    "airWaybillNumber" : "020-77353780",
    "originAndDestination" : {
      "origin" : "VRN",
      "destination" : "ORD"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 250,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "consignee notified",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 250,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-14T21:06:00",
      "airportOfNotification" : "ORD",
      "notificationToName" : "RANA MEAL SOLUTION LLC PH 1 646 42"
    } ]
  }, {
    "type" : "flight status",
    "messageHeader" : {
      "addressing" : {
        "senderAddresses" : [ {
          "type" : "PIMA",
          "address" : "REUAIR08DLH"
        } ],
        "finalRecipientAddresses" : [ {
          "type" : "PIMA",
          "address" : "TCMAGT82TCM"
        } ]
      },
      "creationDate" : "2017-06-15T02:06:00",
      "edifactData" : {
        "commonAccessReference" : "1706150206",
        "messageReference" : "MSG",
        "interchangeControlReference" : "21726275"
      }
    },
    "airWaybillNumber" : "020-77353780",
    "originAndDestination" : {
      "origin" : "VRN",
      "destination" : "ORD"
    },
    "shipmentDescriptionCode" : "TOTAL_CONSIGNMENT",
    "numberOfPieces" : 1,
    "weight" : {
      "amount" : 250,
      "unit" : "KILOGRAM"
    },
    "totalNumberOfPieces" : 1,
    "events" : [ {
      "type" : "consignee notified",
      "numberOfPieces" : 1,
      "weight" : {
        "amount" : 250,
        "unit" : "KILOGRAM"
      },
      "timeOfEvent" : "2017-06-14T21:06:00",
      "airportOfNotification" : "ORD",
      "notificationToName" : "RANA MEAL SOLUTION LLC PH 1 646 42"
    } ]
  } ],
  "responseCode" : "OK"
}